{{- if .Values.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    app: {{ include "postfix.name" . }}
    chart: {{ include "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "postfix.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "postfix.name" . }}
        chart: {{ template "postfix.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
      {{- range $key, $value := .Values.postfix.templates }}
        checksum/{{ $key }}: {{ $value | toYaml | sha256sum }}
      {{- end }}
{{- with .Values.daemonset.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.daemonset.useHostNetwork }}
      hostNetwork: {{ .Values.daemonset.useHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          postStart:
            exec:
              command: ["/usr/sbin/postmap", "/etc/postfix/sasl_passwd"]
          preStop:
            exec:
              command: ["/usr/sbin/postfix", "flush"]
        ports:
        - name: smtp
          containerPort: 25
          {{- if .Values.daemonset.hostPort }}
          hostPort: {{ .Values.daemonset.hostPort }}
          {{- end }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 25
          failureThreshold: 2
          initialDelaySeconds: 10
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 25
          failureThreshold: 2
          periodSeconds: 5
        volumeMounts:
        - name: configmap-postfix
          subPath: main-cf
          mountPath: /etc/postfix/main.cf
        - name: secret-postfix
          subPath: sasl_passwd
          mountPath: /etc/postfix/sasl_passwd
          readOnly: true
{{- if .Values.extraVolumeMounts }}
{{ tpl .Values.extraVolumeMounts . | indent 8 }}
{{- end }}
      {{- if .Values.test.enabled }}
      - name: {{ .Chart.Name }}-mailhog
        image: mailhog/mailhog
        ports:
          - name: hog-smtp
            containerPort: 1025
            protocol: TCP
          - name: hog-http
            containerPort: 8025
            hostPort: {{ .Values.test.mailHogHttpPort }}
            protocol: TCP
      {{- end }}
      volumes:
      - name: configmap-postfix
        configMap:
          name: {{ template "postfix.fullname" . }}-configmap-postfix
      - name: secret-postfix
        secret:
          secretName: {{ template "postfix.fullname" . }}-secret-postfix
{{- if .Values.extraVolumes }}
{{ tpl .Values.extraVolumes . | indent 6 }}
{{- end }}
{{- with .Values.resources }}
      resources:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.daemonset.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.daemonset.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.daemonset.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      updateStrategy:
        type: {{ default "RollingUpdate" .Values.daemonset.updateStrategy | quote }}
{{- end }}
