{{- if .Values.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "postfix.fullname" . }}
  labels: {{ include "postfix.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "postfix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "postfix.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.postfix.secrets.sasl_passwd }}
        checksum/sasl_passwd: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.daemonset.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.daemonset.useHostNetwork }}
      hostNetwork: {{ .Values.daemonset.useHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 12 }}
        {{- end }}
        lifecycle: {{ toYaml .Values.daemonset.lifecycle | nindent 10 }}
        ports:
          - name: smtp
            containerPort: 25
            {{- with .Values.daemonset.hostPort }}
            hostPort: {{ . }}
            {{- end }}
            protocol: TCP
        livenessProbe: {{ toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe: {{ toYaml .Values.readinessProbe | nindent 10 }}
        volumeMounts:
          - name: spool
            mountPath: /var/spool/postfix
            {{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}
            {{- end }}
          {{- range $k, $v := .Values.postfix.templates }}
          - name: configmap
            subPath: {{ $k }}
            mountPath: /etc/postfix/{{ $k }}
          {{- end }}
          {{- if .Values.postfix.secrets.sasl_passwd }}
          - name: secret
            subPath: sasl_passwd
            mountPath: /etc/postfix/sasl_passwd
            readOnly: true
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          {{ toYaml .Values.extraVolumeMounts | nindent 10 }}
          {{- end }}
      {{- if .Values.metrics.enabled }}
      - name: exporter
        image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        {{- with .Values.metrics.command }}
        command: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.metrics.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        {{- with .Values.metrics.livenessProbe }}
        livenessProbe: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.metrics.readinessProbe }}
        readinessProbe: {{ toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: spool
          mountPath: /var/spool/postfix
          {{- if .Values.persistence.subPath }}
          subPath: {{ .Values.persistence.subPath }}
          {{- end }}
          readOnly: true
        {{- if .Values.extraVolumeMounts }}
        {{ toYaml .Values.extraVolumeMounts | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
        - name: spool
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "postfix.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: configmap
          configMap:
            name: {{ template "postfix.fullname" . }}-configmap
        {{- if .Values.postfix.secrets.sasl_passwd }}
        - name: secret
          secret:
            secretName: {{ template "postfix.fullname" . }}-secret
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- with .Values.daemonset.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonset.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: {{ .Values.daemonset.updateStrategy }}
{{- end }}
