{{- if .Values.mailhog.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix.fullname" . }}-mailhog
  labels:
    app: {{ include "postfix.name" . }}-mailhog
    chart: {{ include "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 1025
      protocol: TCP
      name: smtp
    - port: 8025
      nodePort: {{ .Values.mailhog.hostHttpPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "postfix.name" . }}-mailhog
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postfix.fullname" . }}-mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postfix.name" . }}-mailhog
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "postfix.name" . }}-mailhog
        chart: {{ template "postfix.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-mailhog
          image: mailhog/mailhog
          ports:
            - name: smtp
              containerPort: 1025
              protocol: TCP
            - name: http
              containerPort: 8025
              protocol: TCP
{{- end }}
