{{- $root := .Values.mailcatcher -}}
{{- if $root.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix.fullname" . }}-mailcatcher
  labels:
    {{- include "postfix-mailcatcher.labels" . | nindent 4 }}
spec:
  type: {{ $root.service.type }}
  ports:
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smtp
    - port: {{ $root.service.httpPort }}
      targetPort: 1080
      protocol: TCP
      name: http
  selector:
    {{- include "postfix-mailcatcher.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postfix.fullname" . }}-mailcatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postfix-mailcatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postfix-mailcatcher.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "postfix.name" . }}-mailcatcher
          image: "{{ $root.image.repository }}:{{ $root.image.tag }}"
          imagePullPolicy: {{ $root.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: 1025
              protocol: TCP
            - name: http
              containerPort: 1080
              protocol: TCP
          {{- with $root.livenessProbe }}
          livenessProbe:
            {{- toYaml .| nindent 12 }}
          {{- end }}
          {{- with $root.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
