{{- if and .Values.deployment.enabled .Values.deployment.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
spec:
  {{- with .Values.deployment.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end  }}
  {{- with .Values.deployment.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end  }}
  selector:
    matchLabels:
      app: {{ include "postfix.name" . }}
      release: {{ .Release.Name }}
{{- end }}

