{{- if .Values.postfix.secrets.sasl_passwd }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postfix.fullname" . }}-secret
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  sasl_passwd: {{ tpl .Values.postfix.secrets.sasl_passwd . | b64enc | quote }}
{{- end }}