RELEASE = "$$(basename $$PWD)"

.PHONY: install
install:
	echo "no install"
	echo "This application cannot be launched without AWS privileges."

.PHONY: test
test:
	echo "no test"

.PHONY: uninstall
uninstall:
	helm uninstall $(RELEASE)
