{{- $root := . }}
{{- range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  labels:
    {{- include "argoproj-crd.labels" $root | nindent 4 }}
    {{- with $app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ $app.server }}
    namespace: {{ $app.namespace }}

{{- with $app.ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with $app.info }}
  info:
    {{- toYaml . | nindent 4 }}
{{- end }}
  project: {{ $root.Values.project.name }}
{{- with $app.revisionHistoryLimit }}
  revisionHistoryLimit:
    {{- toYaml . | nindent 4 }}
{{- end }}
  source:
{{- with $app.chart }}
    chart:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- with $app.directory }}
    directory:
      {{- toYaml .| nindent 6 }}
{{- end }}
{{- with $app.helm }}
    helm:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- with $app.ksonnet }}
    ksonnet:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- with $app.kustomize }}
    kustomize:
      {{- toYaml . | nindent 6 }}
{{- end }}
    path: {{ $app.path }}
{{- with $app.plugin }}
    plugin:
      {{- toYaml . | nindent 6 }}
{{- end }}
    repoURL: {{ $app.repoURL }}
    targetRevision: {{ $app.targetRevision }}
{{- with $app.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
