apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name }}
  labels:
    {{- include "argoproj-crd.labels" . | nindent 4 }}
    {{- with .Values.project.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  description: {{ .Values.project.description }}
  sourceRepos:
    {{- include "argoproj-crd.sourceRepos" . | splitList "," | uniq | toYaml | nindent 4 }}
  sourceNamespaces:
    {{- include "argoproj-crd.sourceNamespaces" . | splitList "," | uniq | toYaml | nindent 4 }}

  destinations:
    {{- toYaml .Values.project.destinations | nindent 4}}

  clusterResourceWhitelist:
    {{- toYaml .Values.project.clusterResourceWhitelist | nindent 4}}
  {{- if .Values.project.namespaceResourceBlacklist }}
  namespaceResourceBlacklist:
    {{- toYaml .Values.project.namespaceResourceBlacklist | nindent 4}}
  {{- end }}
  {{- if .Values.project.namespaceResourceWhitelist }}
  namespaceResourceWhitelist:
    {{- toYaml .Values.project.namespaceResourceBlacklist | nindent 4}}
  {{- end }}
  {{- if .Values.project.orphanedResources }}
  orphanedResources:
    {{- toYaml .Values.project.orphanedResources | nindent 4}}
  {{- end }}
  {{- if .Values.project.roles }}
  roles:
    {{- toYaml .Values.project.roles | nindent 4}}
  {{- end }}
  {{- if .Values.project.syncWindows }}
  syncWindows:
    {{- toYaml .Values.project.syncWindows | nindent 4}}
  {{- end }}
