{{- if or .Values.config.monitor.istio .Values.config.monitor.serviceAccounts }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "twistlock-defender.fullname" . }}
  labels:
    app: "{{ template "twistlock-defender.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "twistlock-defender.fullname" . }}
subjects:
- apiGroup:
  kind: ServiceAccount
  name: {{ template "twistlock-defender.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end}}
