{{- if or .Values.config.monitor.istio .Values.config.monitor.serviceAccounts }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "twistlock-defender.fullname" . }}
  labels:
    app: {{ template "twistlock-defender.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules:
{{- with .Values.config.monitor.serviceAccounts }}
# Allow Defenders to list RBAC resources
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  - "clusterroles"
  - "clusterrolebindings"
  verbs: ["list"]
{{- end }}
{{- with .Values.config.monitor.istio }}
# Allow Defenders to list Istio RBAC resources
- apiGroups:
  - "rbac.istio.io"
  resources:
  - "rbacconfigs"
  - "servicerolebindings"
  - "serviceroles"
  verbs:
  - "list"
 # Allow Defenders to list Istio authorization policies
- apiGroups:
  - "security.istio.io"
  resources:
  - "authorizationpolicies"
  verbs:
  - "list"
# Allow Defenders to list Istio mesh policies
- apiGroups:
  - "authentication.istio.io"
  resources:
  - "meshpolicies"
  verbs:
  - "list"
# Allow Defenders to list Istio networking resources
- apiGroups:
  - "networking.istio.io"
  resources:
  - "virtualservices"
  - "destinationrules"
  - "gateways"
  - "serviceentries"
  verbs:
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  - "endpoints"
  - "services"
  verbs:
  - "list"
{{- end }}
{{- with .Values.config.collectPodLabels}}
# Allow Defenders to get Deployments and ReplicaSets
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "replicasets"
  verbs:
  - "get"
# Allow Defenders to get Namespaces and Pods
- apiGroups:
  - "" # Core API
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
{{- end }}
{{- if .Values.config.microsegmentation}}
- apiGroups:
  - ""
  resources:
  - "nodes"
  verbs:
  - "get"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
  - "update"
{{- end }}
{{- end }}
