apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twistlock-defender.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "twistlock-defender.labels" . | nindent 4 }}
type: Opaque
data:
  service-parameter: {{ .Values.secret.service_parameter }}
  ca.pem: {{ .Values.secret.ca_cert }}
  client-cert.pem: {{ .Values.secret.client_cert }}
  client-key.pem: {{ .Values.secret.client_key }}
