apiVersion: v1
kind: Secret
metadata:
  name: {{ template "twistlock-defender.fullname" . }}
  labels:
    app: {{ template "twistlock-defender.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  service-parameter: {{ .Values.secret.service_parameter }}
  ca.pem: {{ .Values.secret.ca_cert }}
  client-cert.pem: {{ .Values.secret.client_cert }}
  client-key.pem: {{ .Values.secret.client_key }}
