apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "twistlock-defender.fullname" . }}
  labels:
    app: {{ template "twistlock-defender.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
secrets:
- name: {{ template "twistlock-defender.fullname" . }}
