apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "twistlock-defender.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "twistlock-defender.labels" . | nindent 4 }}
secrets:
  - name: {{ include "twistlock-defender.fullname" . }}
