apiVersion: v1
kind: Service
metadata:
  name: {{ template "sendgrid2datadog.fullname" . }}
  labels:
    app: {{ template "sendgrid2datadog.name" . }}
    chart: {{ template "sendgrid2datadog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port | default .Values.api.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ template "sendgrid2datadog.name" . }}
    release: {{ .Release.Name }}
