{{- $root := . -}}
{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluent-bit.fullname" $root }}-{{ $name | replace "." "-" | replace "_" "-" | lower }}
  labels:
    {{- include "fluent-bit.labels" $root | nindent 4 }}
type: Opaque
data:
  {{ $name }}: {{ tpl $secret $root | b64enc | quote }}
{{- end }}
