{{- $root := . -}}
{{- if .Values.nginx.enabled }}
{{- range $name, $tmpl := .Values.nginx.templates }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "php.labels" $root | nindent 4 }}
  name: {{ include "php.fullname" $root }}-nginx-{{ $name | replace "." "-" | lower }}
data:
  {{- if eq (kindOf $tmpl) "string" }}
  {{ $name }}: |
    {{- tpl $tmpl $root | nindent 4 }}
  {{- else }}
  {{- range $k, $v := $tmpl }}
  {{ $k }}: {{ tpl $v $root | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}