{{- $root := . -}}
{{- range $name, $tmpl := .Values.busybox.templates }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "php.fullname" $root }}-busybox-{{ $name | replace "." "-" | lower }}"
  labels: "{{ include "php.labels" $root | nindent 4 }}"
  annotations:
    {{- range $k, $v := $root.Values.busybox.annotations }}
    {{ $k }}: "{{ tpl $v $root }}"
    {{- end }}
data:
  {{- if eq (kindOf $tmpl) "string" }}
  {{ $name }}: |
    {{- tpl $tmpl $root | nindent 4 }}
  {{- else }}
  {{- range $k, $v := $tmpl }}
  {{ $k }}: "{{ tpl $v $root }}"
  {{- end }}
  {{- end }}
{{- end }}