{{- $root := . -}}
{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "php.ingress.apiVersion" . }}
kind: Ingress
metadata:
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.ingress.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  name: {{ include "php.fullname" . }}
spec:
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .extraPathes }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          - path: {{ .path }}
            backend:
              serviceName: {{ include "php.fullname" $root }}
              {{- if $root.Values.nginx.enabled }}
              servicePort: {{ $root.Values.service.port | default $root.Values.nginx.containerPort }}
              {{- else }}
              servicePort: {{ $root.Values.service.port | default $root.Values.fpm.containerPort }}
              {{- end }}
    {{- end }}
{{- end }}
