{{- $root := . -}}
{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "php.ingress.apiVersion" . }}
kind: Ingress
metadata:
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.ingress.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  name: {{ include "php.fullname" . }}
spec:
  backend:
    serviceName: {{ include "php.fullname" . }}
    {{- if .Values.nginx.enabled }}
    servicePort: {{ .Values.service.port | default .Values.nginx.containerPort }}
    {{- else }}
    servicePort: {{ .Values.service.port | default .Values.fpm.containerPort }}
    {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host $root }}
      http:
        paths:
          {{- with $root.Values.ingress.preferPaths }}
          {{- tpl (toYaml .) $root | nindent 10 }}
          {{- end }}
          - path: /*
            backend:
              serviceName: {{ include "php.fullname" $root }}
              {{- if $root.Values.nginx.enabled }}
              servicePort: {{ $root.Values.service.port | default $root.Values.nginx.containerPort }}
              {{- else }}
              servicePort: {{ $root.Values.service.port | default $root.Values.fpm.containerPort }}
              {{- end }}
    {{- end }}
{{- end }}
