{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    {{- range $k, $v := .Values.podDisruptionBudget.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.podDisruptionBudget.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  name: {{ include "php.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "php.selectorLabels" . | nindent 6 }}
{{- end }}
