{{- if and .Values.rbac.create .Values.podSecurityPolicy.create }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    {{- range $k, $v := .Values.podSecurityPolicy.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.podSecurityPolicy.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  name: {{ include "php.podSecurityPolicyName" . }}
spec:
  privileged: false
  seLinux:
    {{- toYaml .Values.podSecurityPolicy.seLinux | nindent 4 }}
  supplementalGroups:
    {{- toYaml .Values.podSecurityPolicy.supplementalGroups | nindent 4 }}
  runAsUser:
    {{- toYaml .Values.podSecurityPolicy.runAsUser | nindent 4 }}
  fsGroup:
    {{- toYaml .Values.podSecurityPolicy.fsGroup | nindent 4 }}
  volumes:
    {{- toYaml .Values.podSecurityPolicy.volumes | nindent 4 }}
  allowedUnsafeSysctls:
    {{- range .Values.securityContext.sysctls }}
    - {{ .name }}
    {{- end }}
{{- end }}