{{- if and .Values.rbac.create .Values.psp.create }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    {{- range $k, $v := .Values.psp.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.psp.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  name: {{ include "php.pspName" . }}
spec:
  privileged: false
  seLinux:
    {{- toYaml .Values.psp.seLinux | nindent 4 }}
  supplementalGroups:
    {{- toYaml .Values.psp.supplementalGroups | nindent 4 }}
  runAsUser:
    {{- toYaml .Values.psp.runAsUser | nindent 4 }}
  fsGroup:
    {{- toYaml .Values.psp.fsGroup | nindent 4 }}
  volumes:
    {{- toYaml .Values.psp.volumes | nindent 4 }}
  allowedUnsafeSysctls:
    {{- range .Values.securityContext.sysctls }}
    - {{ .name }}
    {{- end }}
{{- end }}