{{- if .Values.rbac.create }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "{{ template "php.fullname" . }}"
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'
  allowedUnsafeSysctls:
    {{- range .Values.securityContext.sysctls }}
    - '{{ .name }}'
    {{- end }}
{{- end }}