{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "php.fullname" . }}"
  labels:
    {{- include "php.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - "{{ template "php.fullname" . }}"
    verbs:
      - use
{{- end }}