{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "php.labels" . | nindent 4 }}
  name: {{ include "php.fullname" . }}
rules:
  {{- if eq (include "php.enablePodSecurityPolicy" .) "true" }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "php.podSecurityPolicyName" . }}
    verbs:
      - use
  {{- end }}
{{- end }}