{{- $root := . -}}
{{- range $name, $secret := .Values.busybox.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "php.fullname" $root }}-busybox-{{ $name | replace "." "-" | lower }}"
  labels:
    {{- include "php.labels" $root | nindent 4 }}
  annotations:
    {{- range $k, $v := $root.Values.busybox.annotations }}
    {{ $k }}: "{{ tpl $v $root }}"
    {{- end }}
type: Opaque
data:
  {{- if eq (kindOf $secret) "string" }}
  {{ $name }}: "{{ tpl $secret $root | b64enc }}"
  {{- else }}
  {{- range $k, $v := $secret }}
  {{ $k }}: "{{ tpl $v $root | b64enc }}"
  {{- end }}
  {{- end }}
{{- end }}
