{{- $root := . -}}
{{- if .Values.busybox.enabled }}
{{- range $name, $secret := .Values.busybox.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "php.fullname" $root }}-busybox-{{ $name | replace "." "-" | lower }}
  labels: {{ include "php.labels" $root | nindent 4 }}
  {{- with $root.Values.busybox.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $root | toYaml | indent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{- if eq (kindOf $secret) "string" }}
  {{ $name }}: {{ tpl $secret $root | b64enc | quote }}
  {{- else }}
  {{- range $k, $v := $secret }}
  {{ $k }}: {{ tpl $v $root | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}