{{- $root := . -}}
{{- if .Values.busybox.enabled }}
{{- range $name, $secret := .Values.busybox.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "php.labels" $root | nindent 4 }}
  name: {{ include "php.fullname" $root }}-busybox-{{ $name | replace "." "-" | lower }}
type: Opaque
data:
  {{- if eq (kindOf $secret) "string" }}
  {{ $name }}: {{ tpl $secret $root | b64enc | quote }}
  {{- else }}
  {{- range $k, $v := $secret }}
  {{ $k }}: {{ tpl $v $root | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}