{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.service.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  name: {{ include "php.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: default
      {{- if .Values.nginx.enabled }}
      port: {{ .Values.service.port | default .Values.nginx.containerPort }}
      {{- else }}
      port: {{ .Values.service.port | default .Values.fpm.containerPort }}
      {{- end }}
      protocol: TCP
      targetPort: default
    {{- with .Values.service.extraPorts }}
    {{- tpl (toYaml .) $root | nindent 4 }}
    {{- end }}
  selector:
    {{- include "php.selectorLabels" . | nindent 4 }}
