{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "php.fullname" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $root | toYaml | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: default
      {{- if .Values.nginx.enabled }}
      port: {{ .Values.service.port | default .Values.nginx.containerPort }}
      {{- else }}
      port: {{ .Values.service.port | default .Values.fpm.containerPort }}
      {{- end }}
      protocol: TCP
      targetPort: default
    {{- with .Values.service.extraPorts }}
    {{- tpl (toYaml .) $root | nindent 4 }}
    {{- end }}
  selector: {{ include "php.selectorLabels" . | nindent 4 }}
