{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "php.fullname" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - name: default
      port: {{ .Values.service.port | default .Values.nginx.containerPort }}
      protocol: TCP
      targetPort: default
    {{- with .Values.service.extraPorts }}
    {{- tpl (toYaml .) $root | nindent 4 }}
    {{- else }}
    {{- range .Values.nginx.extraPortss }}
    - name: {{ tpl .name $root }}
      port: {{ tpl .containerPort $root }}
      {{- with .protocol }}
      protocol: {{ tpl . $root }}
      {{- end }}
      targetPort: {{ tpl .name $root | default .containerPort }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "php.selectorLabels" . | nindent 4 }}
