{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.serviceAccount.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  name: {{ include "php.serviceAccountName" . }}
{{- end }}
