{{- $root := . -}}
  {{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    {{- toYaml .Values.autoscaling.annotations | nindent 4}}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
    {{- with .Values.autoscaling.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: "{{ template "envoy.fullname" . }}"
spec:
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: "{{ template "envoy.fullname" . }}"
  {{- end }}
