{{- $root := . }}
{{- range $index, $value := .Values.configmaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "slime.labels" $root | nindent 4 }}
  {{- range $key, $val := $value.metadata }}
    {{- if eq $key "labels" }}
    {{- range $k, $v := $value.metadata.labels }}
    {{ $k }}: {{ $v }}
    {{- end }}
  {{- else }}
  {{- if regexMatch "^(string|bool|int|float64)$" (printf "%T" $val) }}
  {{ $key }}: {{ $val }}
  {{- else }}
  {{ $key }}:
    {{- toYaml $val | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- with $value.binaryData }}
binaryData:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- with $value.data }}
data:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
