{{- if .Values.cronJob.enabled -}}
{{- $root := . }}
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#cronjob-v1-batch
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "slime.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.cronJobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "slime.labels" . | nindent 4 }}
    {{- with .Values.cronJobLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#cronjobspec-v1-batch
spec:
  {{- with .Values.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  schedule: "{{ .Values.schedule }}"
  {{- with .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.suspend }}
  suspend: {{ . }}
  {{- end }}
  # Available in 1.27 or later
  # https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-job-limitations
  {{- with .Values.timeZone }}
  timeZone: {{ . }}
  {{- end }}
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#jobtemplatespec-v1-batch
  jobTemplate:
    metadata:
      {{- with .Values.cronJobTemplateAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "slime.labels" . | nindent 8 }}
      {{- with .Values.cronJobTemplateLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#jobspec-v1-batch
      {{- with .Values.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      {{- with .Values.backoffLimit }}
      backoffLimit: {{ . }}
      {{- end }}
      {{- with .Values.completionMode }}
      completionMode: {{ . }}
      {{- end }}
      {{- with .Values.completions }}
      completions: {{ . }}
      {{- end }}
      {{- with .Values.manualSelector }}
      manualSelector: {{ . }}
      {{- end }}
      {{- with .Values.parallelism }}
      parallelism: {{ . }}
      {{- end }}
      {{- with .Values.jobTemplateSuspend }}
      suspend: {{ . }}
      {{- end }}
      {{- with .Values.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      template:
        metadata:
          {{- with .Values.cronJobPodAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
          {{- include "slime.labels" . | nindent 12 }}
          {{- with .Values.cronJobPodLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.cronJobPodActiveDeadlineSeconds }}
          activeDeadlineSeconds: {{ . }}
          {{- end }}
          {{- with .Values.cronJobAffinity }}
          affinity:
            {{- tpl (. | toYaml) $root | nindent 14 }}
          {{- end }}
          {{- with .Values.automountServiceAccountToken }}
          automountServiceAccountToken: {{ . }}
          {{- end }}
          containers:
            {{- range $container := .Values.cronJobContainers }}
            - name: {{ include "slime.fullname" $root }}-{{ $container.name }}
              {{- with $container.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: {{ $container.image.repository }}:{{ $container.image.tag }}
              {{- with $container.image.pullPolicy }}
              imagePullPolicy: {{ . }}
              {{- end }}
              {{- with $container.ports }}
              ports:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $container.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $container.workingDir }}
              workingDir: {{ . }}
              {{- end }}
              {{- with $container.env }}
              env:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.envFrom }}
              envFrom:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.lifecycle }}
              lifecycle:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $container.startupProbe }}
              startupProbe:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.readinessProbe }}
              readinessProbe:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.livenessProbe }}
              livenessProbe:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $container.volumeMounts }}
              volumeMounts:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- with .Values.cronJobDnsConfig }}
          dnsConfig:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.cronJobUseHostNetwork }}
          hostNetwork: {{ .Values.cronJobUseHostNetwork }}
          dnsPolicy: ClusterFirstWithHostNet
          {{- end }}
          {{- if and (not .Values.cronJobUseHostNetwork) .Values.cronJobDnsPolicy }}
          dnsPolicy: {{ .Values.cronJobDnsPolicy }}
          {{- end }}
          {{- with .Values.cronJobEnableServiceLinks }}
          enableServiceLinks: {{ . }}
          {{- end }}
          {{- with .Values.cronJobHostAliases }}
          hostAliases:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronJobHostIPC }}
          hostIPC: {{ . }}
          {{- end }}
          {{- with .Values.cronJobHostPID }}
          hostPID: {{ . }}
          {{- end }}
          {{- with .Values.cronJobHostUsers }}
          hostUsers: {{ . }}
          {{- end }}
          {{- with .Values.cronJobHostname }}
          hostname: {{ . }}
          {{- end }}
          {{- with .Values.cronJobImagePullSecrets }}
          imagePullSecrets:
            {{- tpl (. | toYaml) $root | nindent 12 }}
          {{- end }}
          {{- if .Values.cronJobInitContainers.enabled }}
          initContainers:
          {{- range $container := .Values.cronJobInitContainers.containers }}
            - name: {{ include "slime.fullname" $root }}-{{ $container.name }}
              image: {{ $container.image.repository }}:{{ $container.image.tag }}
              {{- with $container.image.pullPolicy }}
              imagePullPolicy: {{ . }}
              {{- end }}
              {{- with $container.command }}
              command:
                {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- with $container.args }}
              args:
                {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- with $container.workingDir }}
              workingDir: {{ . }}
              {{- end }}
              {{- with $container.env }}
              env:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.envFrom }}
              envFrom:
                {{- tpl (. | toYaml) $root | nindent 14 }}
              {{- end }}
              {{- with $container.volumeMounts }}
              volumeMounts:
                {{- tpl (. | toYaml) $root | nindent 14 }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.cronJobNodeName }}
          nodeName: {{ . }}
          {{- end }}
          {{- with .Values.cronJobNodeSelector }}
          nodeSelector:
            {{- tpl (. | toYaml) $root | nindent 12 }}
          {{- end }}
          {{- with .Values.cronJobPreemptionPolicy }}
          preemptionPolicy: {{ . }}
          {{- end }}
          {{- with .Values.cronJobPriority }}
          priority: {{ . }}
          {{- end }}
          {{- with .Values.cronJobPriorityClassName }}
          priorityClassName: {{ . }}
          {{- end }}
          {{- if .Values.cronJobRestartPolicy }}
          restartPolicy: {{ .Values.cronJobRestartPolicy }}
          {{- else }}
          restartPolicy: "OnFailure"
          {{- end }}
          {{- with .Values.cronJobSchedulerName }}
          schedulerName: {{ . }}
          {{- end }}
          serviceAccountName: {{ include "slime.serviceAccountName" . }}
          {{- with .Values.cronJobSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronJobSetHostnameAsFQDN }}
          setHostnameAsFQDN: {{ . }}
          {{- end }}
          {{- with .Values.cronJobShareProcessNamespace }}
          shareProcessNamespace: {{ . }}
          {{- end }}
          {{- with .Values.cronJobSubdomain }}
          subdomain: {{ . }}
          {{- end }}
          {{- with .Values.cronJobTerminationGracePeriodSeconds }}
          terminationGracePeriodSeconds: {{ . }}
          {{- end }}
          {{- with .Values.cronJobTolerations }}
          tolerations:
            {{- tpl (. | toYaml) $root | nindent 12 }}
          {{- end }}
          {{- if .Values.cronJobTopologySpreadConstraints.enabled }}
          topologySpreadConstraints:
            {{- range $constraint := .Values.cronJobTopologySpreadConstraints.constraints }}
            - maxSkew: {{ $constraint.maxSkew }}
              topologyKey: {{ $constraint.topologyKey }}
              whenUnsatisfiable: {{ $constraint.whenUnsatisfiable }}
              labelSelector:
                matchLabels:
                  {{- include "slime.selectorLabels" $root | nindent 18 }}
            {{- end }}
          {{- end }}
          {{- with .Values.cronJobVolumes }}
          volumes:
            {{- tpl (. | toYaml) $root | nindent 12 }}
          {{- end }}
{{- end }}
