{{- if .Values.cronJob.enabled -}}
{{- $root := . }}
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#cronjob-v1-batch
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "slime.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.cronJob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "slime.labels" . | nindent 4 }}
    {{- with .Values.cronJob.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#cronjobspec-v1-batch
spec:
  {{- with .Values.cronJob.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.cronJob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  schedule: "{{ .Values.cronJob.schedule }}"
  {{- with .Values.cronJob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.cronJob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.cronJob.suspend }}
  suspend: {{ . }}
  {{- end }}
  # Available in 1.27 or later
  # https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-job-limitations
  {{- with .Values.cronJob.timeZone }}
  timeZone: {{ . }}
  {{- end }}
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#jobtemplatespec-v1-batch
  jobTemplate:
    metadata:
      {{- with .Values.cronJob.jobTemplate.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "slime.labels" . | nindent 8 }}
      {{- with .Values.cronJob.jobTemplate.jobTemplatelabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#jobspec-v1-batch
      {{- with .Values.cronJob.jobTemplate.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      {{- with .Values.cronJob.jobTemplate.backoffLimit }}
      backoffLimit: {{ . }}
      {{- end }}
      {{- with .Values.cronJob.jobTemplate.completionMode }}
      completionMode: {{ . }}
      {{- end }}
      {{- with .Values.cronJob.jobTemplate.completions }}
      completions: {{ . }}
      {{- end }}
      {{- with .Values.cronJob.jobTemplate.manualSelector }}
      manualSelector: {{ . }}
      {{- end }}
      {{- with .Values.cronJob.jobTemplate.parallelism }}
      parallelism: {{ . }}
      {{- end }}
      {{- with .Values.cronJob.jobTemplate.suspend }}
      suspend: {{ . }}
      {{- end }}
      {{- with .Values.cronJob.jobTemplate.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      template:
        metadata:
          {{- with .Values.cronJob.jobTemplate.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
          {{- include "slime.labels" . | nindent 12 }}
          {{- with .Values.cronJob.jobTemplate.podLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.cronJob.jobTemplate.activeDeadlineSeconds }}
          activeDeadlineSeconds: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.affinity }}
          affinity:
            {{- tpl (. | toYaml) $root | nindent 14 }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.automountServiceAccountToken }}
          automountServiceAccountToken: {{ . }}
          {{- end }}
          containers:
            {{- range $container := .Values.cronJob.jobTemplate.containers }}
            - name: {{ include "slime.fullname" $root }}-{{ $container.name }}
              {{- with $container.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: {{ $container.image.repository }}:{{ $container.image.tag }}
              {{- with $container.image.pullPolicy }}
              imagePullPolicy: {{ . }}
              {{- end }}
              {{- with $container.ports }}
              ports:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $container.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $container.workingDir }}
              workingDir: {{ . }}
              {{- end }}
              {{- with $container.env }}
              env:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.envFrom }}
              envFrom:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.lifecycle }}
              lifecycle:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $container.startupProbe }}
              startupProbe:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.readinessProbe }}
              readinessProbe:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.livenessProbe }}
              livenessProbe:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $container.volumeMounts }}
              volumeMounts:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- with .Values.cronJob.jobTemplate.dnsConfig }}
          dnsConfig:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.cronJob.jobTemplate.useHostNetwork }}
          hostNetwork: {{ .Values.cronJob.jobTemplate.useHostNetwork }}
          dnsPolicy: ClusterFirstWithHostNet
          {{- end }}
          {{- if and (not .Values.cronJob.jobTemplate.useHostNetwork) .Values.cronJob.jobTemplate.dnsPolicy }}
          dnsPolicy: {{ .Values.cronJob.jobTemplate.dnsPolicy }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.enableServiceLinks }}
          enableServiceLinks: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.hostAliases }}
          hostAliases:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.hostIPC }}
          hostIPC: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.hostPID }}
          hostPID: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.hostUsers }}
          hostUsers: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.hostname }}
          hostname: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.imagePullSecrets }}
          imagePullSecrets:
            {{- tpl (. | toYaml) $root | nindent 12 }}
          {{- end }}
          {{- if .Values.cronJob.jobTemplate.initContainers.enabled }}
          initContainers:
          {{- range $container := .Values.cronJob.jobTemplate.initContainers.containers }}
            - name: {{ include "slime.fullname" $root }}-{{ $container.name }}
              image: {{ $container.image.repository }}:{{ $container.image.tag }}
              {{- with $container.image.pullPolicy }}
              imagePullPolicy: {{ . }}
              {{- end }}
              {{- with $container.command }}
              command:
                {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- with $container.args }}
              args:
                {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- with $container.workingDir }}
              workingDir: {{ . }}
              {{- end }}
              {{- with $container.env }}
              env:
                {{- tpl (. | toYaml) $root | nindent 16 }}
              {{- end }}
              {{- with $container.envFrom }}
              envFrom:
                {{- tpl (. | toYaml) $root | nindent 14 }}
              {{- end }}
              {{- with $container.volumeMounts }}
              volumeMounts:
                {{- tpl (. | toYaml) $root | nindent 14 }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.nodeName }}
          nodeName: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.nodeSelector }}
          nodeSelector:
            {{- tpl (. | toYaml) $root | nindent 12 }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.preemptionPolicy }}
          preemptionPolicy: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.priority }}
          priority: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.priorityClassName }}
          priorityClassName: {{ . }}
          {{- end }}
          {{- if .Values.cronJob.jobTemplate.restartPolicy }}
          restartPolicy: {{ .Values.cronJob.jobTemplate.restartPolicy }}
          {{- else }}
          restartPolicy: "OnFailure"
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.schedulerName }}
          schedulerName: {{ . }}
          {{- end }}
          serviceAccountName: {{ include "slime.serviceAccountName" . }}
          {{- with .Values.cronJob.jobSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.setHostnameAsFQDN }}
          setHostnameAsFQDN: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.shareProcessNamespace }}
          shareProcessNamespace: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.subdomain }}
          subdomain: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.terminationGracePeriodSeconds }}
          terminationGracePeriodSeconds: {{ . }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.tolerations }}
          tolerations:
            {{- tpl (. | toYaml) $root | nindent 12 }}
          {{- end }}
          {{- if .Values.cronJob.jobTemplate.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- range $constraint := .Values.cronJob.jobTemplate.topologySpreadConstraints }}
            - maxSkew: {{ $constraint.maxSkew }}
              topologyKey: {{ $constraint.topologyKey }}
              whenUnsatisfiable: {{ $constraint.whenUnsatisfiable }}
              labelSelector:
                matchLabels:
                  {{- include "slime.selectorLabels" $root | nindent 18 }}
            {{- end }}
          {{- end }}
          {{- with .Values.cronJob.jobTemplate.volumes }}
          volumes:
            {{- tpl (. | toYaml) $root | nindent 12 }}
          {{- end }}
{{- end }}
