# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deployment-v1-apps
{{- if .Values.deployment.enabled -}}
{{- $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slime.fullname" $root }}
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  labels:
    app: {{ template "slime.name" $root }}
    chart: {{ template "slime.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "slime.name" $root }}
      release: {{ $root.Release.Name | quote }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.deployment.extraField }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  template:
    metadata:
      name: {{ include "slime.fullname" $root }}
      annotations:
        {{- toYaml .Values.deployment.annotations | nindent 8 }}
      labels:
        app: {{ template "slime.name" $root }}
        release: {{ $root.Release.Name | quote }}
        {{- with .Values.deployment.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        {{- toYaml .Values.deployment.pod.affinity | nindent 8 }}
      containers:
        {{- tpl (toYaml .Values.deployment.pod.container) $root | nindent 8 }}
      {{- with .Values.deployment.pod.extraField }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
