{{- $root := . }}
{{- range $name, $value := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slime.fullname" $root }}-{{ $name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "slime.labels" $root | nindent 4 }}
    {{- with $value.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    checksum/secret: '{{ toYaml $value | sha256sum }}'
    {{- with $value.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if and (semverCompare ">=1.19-0" $root.Capabilities.KubeVersion.GitVersion) $value.immutable }}
immutable: {{ $value.immutable }}
{{- end }}
{{- with $value.data }}
data:
{{- range $k, $v :=  $value.data }}
  {{ $k }}: {{ . | b64enc | quote }}
{{- end }}
{{- with $value.stringData }}
stringData:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- with $value.type }}
type:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
