{{- if .Values.service.enabled }}
{{- $root := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slime.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "slime.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    {{- range $name, $v := .Values.service.ports }}
    - name: {{ $name }}
      targetPort: {{ $v.targetPort }}
      port: {{ $v.port }}
      {{- if and (eq $root.Values.service.type "NodePort") $v.nodePort }}
      nodePort: {{ $v.nodePort }}
      {{- end }}
      protocol: {{ $v.protocol }}
    {{- end }}
  selector:
    {{- include "slime.selectorLabels" . | nindent 4 }}
{{- end }}
