apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twistlock-console.fullname" . }}
  labels:
    {{- include "twistlock-console.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.configmap) . | nindent 2 }}
