{{ $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twistlock-console.fullname" $root }}
  labels:
    {{- include "twistlock-console.labels" $root | nindent 4 }}
data:
  {{- tpl (toYaml .Values.configmap) $root | nindent 2 }}
