{{- $root := . -}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "twistlock-console.fullname" $root }}
  labels:
    {{- include "twistlock-console.labels" $root | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
{{- with .Values.ingress.tls }}
  tls:{{ tpl (toYaml .) $root | nindent 2 }}
{{- end }}
{{- with .Values.ingress.rules }}
  rules:{{ tpl (toYaml .) $root | nindent 2 }}
{{- end }}
{{- end }}
