{{ $root := . }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "twistlock-console.fullname" $root }}
  labels:
    {{- include "twistlock-console.labels" $root | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage.size }}
  storageClassName: {{ .Values.persistentVolumeClaim.storage.className }}
  {{- with .Values.persistentVolumeClaim.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
