{{- if .Values.secrets }}
{{ $root := . }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "twistlock-console.fullname" $root }}
type: Opaque
data:
{{- with .Values.secrets }}
{{ tpl (toYaml .) $root | indent 4 }}
{{- end }}
{{- end}}
