{{- if .Values.secrets }}
{{ $root := . }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "twistlock-console.fullname" $root }}
  labels:
    {{- include "twistlock-console.labels" $root | nindent 4 }}
type: Opaque
{{- with .Values.secrets }}
data:
  {{- tpl (toYaml .) $root | nindent 2 }}
{{- end }}
{{- end}}
