{{ $root := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twistlock-console.fullname" $root }}
  labels:
    {{- include "twistlock-console.labels" $root | nindent 4 }}
  annotations:
    {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.service.clusterIP (eq "ClusterIP" .Values.service.type) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end}}
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.port.communication.name }}
    port: {{ .Values.port.communication.servicePort }}
    targetPort: {{ .Values.port.communication.name }}
    protocol: TCP
  - name: {{ .Values.port.management.https.name }}
    port: {{ .Values.port.management.https.servicePort }}
    targetPort: {{ .Values.port.management.https.name }}
    protocol: TCP
  {{- if .Values.config.management.http.enabled }}
  - name: {{ .Values.port.management.http.name }}
    port: {{ .Values.port.management.http.servicePort }}
    targetPort: {{ .Values.port.management.http.name }}
    protocol: TCP
  {{- end}}
  selector:
    {{- include "twistlock-console.selectorLabels" $root | nindent 4 }}
