{{ $root := . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "twistlock-console.serviceAccountName" $root }}
  labels:
    {{- include "twistlock-console.labels" $root | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
