{{ $root := . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "twistlock-console.labels" $root | nindent 4 }}
  name: {{ include "twistlock-console.fullname" $root }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.service.clusterIP (eq "ClusterIP" .Values.service.type) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end}}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.port.communication.port }}
    targetPort: {{ .Values.port.communication.name }}
  - port: {{ .Values.port.management.https.port }}
    targetPort: {{ .Values.port.management.https.name }}
  {{- if .Values.config.management.http.enabled }}
  - port: {{ .Values.port.management.http.port }}
    targetPort: {{ .Values.port.management.http.name }}
  {{- end}}
  selector:
    {{- include "twistlock-console.selectorLabels" $root | nindent 4 }}
