{{ $root := . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "twistlock-console.fullname" $root }}
    release: {{ .Release.Name }}
  name: {{ template "twistlock-console.fullname" $root }}
spec:
  {{- if and .Values.service.clusterIP (eq "ClusterIP" .Values.service.type) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end}}
  type: {{ .Values.service.type }}
  ports:
  - name: communication
    port: {{ .Values.port.communication }}
  - name: mgmt-https
    port: {{ .Values.port.management.https }}
  {{- if .Values.config.management.http.enabled }}
  - name: mgmt-http
    port: {{ .Values.port.management.http }}
  {{- end}}
  {{- if .Values.config.highAvailability.enabled }}
  - name: ha
    port: {{ .Values.port.highAvailability }}
  {{- end}}
  selector:
    app: {{ template "twistlock-console.fullname" $root }}
    release: {{ .Release.Name }}
