{{- $root := . -}}
{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "http-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-service.labels" . | nindent 4 }}
spec:
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "http-service.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
{{- end }}
