{{- if eq .Values.autoscaling.type "hpa" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "http-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-service.labels" . | nindent 4 }}
spec:
  {{- with (required "autoscaling.hpa.behavior is required when type is hpa" .Values.autoscaling.hpa).behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- toYaml (required "autoscaling.hpa.metrics is required when type is hpa" .Values.autoscaling.hpa.metrics) | nindent 4 }}
  scaleTargetRef:
    {{- if .Values.rollout.enabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "http-service.fullname" . }}
  minReplicas: {{ required "autoscaling.minReplicas is required" .Values.autoscaling.minReplicas }}
  maxReplicas: {{ required "autoscaling.maxReplicas is required" .Values.autoscaling.maxReplicas }}
{{- end }}
