{{- if eq .Values.autoscaling.type "keda" }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "http-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "http-service.fullname" . }}
  minReplicaCount: {{ required "autoscaling.minReplicas is required" .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ required "autoscaling.maxReplicas is required" .Values.autoscaling.maxReplicas }}
  {{- with (required "autoscaling.keda is required when type is keda" .Values.autoscaling.keda).pollingInterval }}
  pollingInterval: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.keda.cooldownPeriod }}
  cooldownPeriod: {{ . }}
  {{- end }}
  triggers:
    {{- toYaml (required "autoscaling.keda.triggers is required when type is keda" .Values.autoscaling.keda.triggers) | nindent 4 }}
{{- end }}
