{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aws-alb-ingress-controller.fullname" . }}
  labels:
    {{- include "aws-alb-ingress-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
      - pods/status
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
{{- if .Values.podSecurityPolicy.create }}
  - apiGroups:
      - policy/v1beta1
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "aws-alb-ingress-controller.fullname" . }}
{{- end }}
{{- end }}
