{{ $root := . }}
{{- with .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "aws-alb-ingress-controller.fullname" $root }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "aws-alb-ingress-controller.labels" $root | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "aws-alb-ingress-controller.instance-labels" $root | nindent 6 }}
{{ toYaml . | indent 2 }}
{{- end }}
