apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlantis-efs-pv-1
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-061819ef222a100b2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: atlantis-efs-sc-1
  volumeMode: Filesystem
