{{- $root := . -}}
{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "fluentd.labels" $root | nindent 4 }}
  name: {{ include "fluentd.fullname" $root }}-{{ $name | replace "." "-" | replace "_" "-" | lower }}
type: Opaque
data:
  {{- if eq (kindOf $secret) "string" }}
  {{ $name }}: {{ tpl $secret $root | b64enc | quote }}
  {{- else }}
  {{- range $k, $v := $secret }}
  {{ $k }}: {{ tpl $v $root | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
