{{- if and .Values.fluentd.http.service.enabled .Values.fluentd.http.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- toYaml .Values.fluentd.http.service.annotations | nindent 4 }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
    {{- with .Values.fluentd.http.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "fluentd.fullname" . }}-http
spec:
  type: {{ .Values.fluentd.http.service.type }}
  ports:
    - port: {{ .Values.fluentd.http.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fluentd.selectorLabels" . | nindent 4 }}
{{- end }}
