---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-attacher-binding
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-provisioner-binding
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-provisioner-role
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.enableVolumeResizing }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-resizer-binding
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-resizer-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.enableVolumeSnapshot }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-snapshot-controller-binding
  labels:
    {{- include "aws-ebs-csi-driver.snapshotController.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.snapshotController.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-snapshot-controller-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.enableVolumeSnapshot }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-snapshotter-binding
  labels:
    {{- include "aws-ebs-csi-driver.snapshotController.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.snapshotController.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
