{{/* AWS Env Secret */}}
{{- if not .Values.controller.awsEnv.secret.existingSecretName }}
{{- if and .Values.controller.awsEnv.secret.keyId .Values.controller.awsEnv.secret.accessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-ebs-csi-driver.controller.awsEnvSecretName" . }}
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
type: Opaque
data:
  keyId: {{ .Values.controller.awsEnv.secret.keyId | b64enc | quote }}
  accessKey: {{ .Values.controller.awsEnv.secret.accessKey | b64enc | quote }}
{{- end }}
{{- end }}
