{{- if .Values.csiProvisoner.leaderElection }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-provisioner-leaderelection
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
{{- end }}
{{- if .Values.csiAttacher.leaderElection }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-attacher-leaderelection
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
{{- end }}
{{- if and .Values.enableVolumeResizing .Values.csiResizer.leaderElection }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-resizer-leaderelection
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
{{- end }}
{{- if and .Values.enableVolumeSnapshot .Values.csiSnapshotter.leaderElection }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-snapshotter-leaderelection
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
{{- end }}
{{- if and .Values.enableVolumeSnapshot .Values.snapshotController.leaderElection }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-snapshot-controller-leaderelection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
{{- end }}
