{{- if .Values.csiProvisoner.leaderElection }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-provisioner-leaderelection
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-provisioner-leaderelection
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.csiAttacher.leaderElection }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-attacher-leaderelection
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-attacher-leaderelection
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if and .Values.enableVolumeResizing .Values.csiResizer.leaderElection }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-resizer-leaderelection
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-resizer-leaderelection
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if and .Values.enableVolumeSnapshot .Values.csiResizer.leaderElection }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-snapshotter-leaderelection
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-external-snapshotter-leaderelection
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if and .Values.enableVolumeSnapshot .Values.snapshotController.leaderElection }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-snapshot-controller-leaderelection
  labels:
    {{- include "aws-ebs-csi-driver.snapshotController.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ebs-csi-driver.snapshotController.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aws-ebs-csi-driver.fullname" . }}-snapshot-controller-leaderelection
  apiGroup: rbac.authorization.k8s.io
{{- end }}
