{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-ebs-csi-driver.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- if .Values.node.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-ebs-csi-driver.node.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver.node.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.node.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- if and .Values.enableVolumeSnapshot .Values.snapshotController.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-ebs-csi-driver.snapshotController.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver.snapshotController.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.snapshotController.serviceAccount.annotations | nindent 4 }}
{{- end }}
