{{/* AWS Env Secret */}}
{{- if .Values.enableVolumeSnapshot }}
{{- if not .Values.snapshotController.awsEnv.secret.existingSecretName }}
{{- if and .Values.snapshotController.awsEnv.secret.keyId .Values.snapshotController.awsEnv.secret.accessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-ebs-csi-driver.snapshotController.awsEnvSecretName" . }}
  labels:
    {{- include "aws-ebs-csi-driver.snapshotController.labels" . | nindent 4 }}
type: Opaque
data:
  keyId: {{ .Values.snapshotController.awsEnv.secret.keyId | b64enc | quote }}
  accessKey: {{ .Values.snapshotController.awsEnv.secret.accessKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
