{{- $root := . -}}
{{- if and .Values.daemonset.enabled (not .Values.deployment.enabled) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "newrelic-php-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
    helm.sh/chart: {{ include "newrelic-php-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    {{- toYaml .Values.daemonset.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.daemonset.useHostNetwork }}
      hostNetwork: {{ .Values.daemonset.useHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.image.command }}
        command:
          {{- toYaml . | nindent 10 }}
{{- end }}
{{- if isAbs $.Values.newrelic.address }}
        args: ["--address={{ $.Values.newrelic.address }}", "--watchdog-foreground"]
{{- end }}
{{- with .Values.daemonset.extraEnv }}
        env:
          {{- toYaml . | nindent 10 }}
{{- end }}
{{- with .Values.daemonset.extraEnvFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
{{- end }}
{{- with .Values.daemonset.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
        livenessProbe:
{{- with .Values.livenessProbe }}
{{ toYaml . | indent 10 }}
{{- else }}
          {{- if isAbs $.Values.newrelic.address }}
          exec:
            command:
            - /bin/sh
            - -c
            - ls -al {{ $.Values.newrelic.address }}
          {{- else }}
          tcpSocket:
            port: {{ $.Values.newrelic.port }}
          {{- end }}
          failureThreshold: 2
          initialDelaySeconds: 10
          periodSeconds: 60
{{- end }}
        readinessProbe:
{{- with .Values.readinessProbe }}
{{ toYaml . | indent 10 }}
{{- else }}
          {{- if isAbs $.Values.newrelic.address }}
          exec:
            command:
            - /bin/sh
            - -c
            - ls -al {{ $.Values.newrelic.address }}
          {{- else }}
          tcpSocket:
            port: {{ $.Values.newrelic.port }}
          {{- end }}
          failureThreshold: 2
          periodSeconds: 5
{{- end }}
{{- if isAbs $.Values.newrelic.address }}
        volumeMounts:
          - mountPath: {{ dir $.Values.newrelic.address }}
            name: newrelic
{{- with .Values.daemonset.extraVolumeMounts }}
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.daemonset.extraPorts }}
        ports:
          {{- toYaml . | nindent 10 }}
{{- end }}
{{- else }}
{{- with .Values.daemonset.extraVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
{{- end }}
        ports:
          - name: nw-daemon-port
            containerPort: {{ $.Values.newrelic.port }}
            protocol: TCP
{{- with .Values.daemonset.extraPorts }}
{{ toYaml . | indent 10 }}
{{- end }}
{{- end }}
{{- if isAbs $.Values.newrelic.address }}
      volumes:
        - name: newrelic
          hostPath:
            path: /var/run/newrelic
{{- with .Values.daemonset.extraVolumes }}
{{ toYaml . | indent 10 }}
{{- end }}
{{- else }}
{{- with .Values.daemonset.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
{{- with .Values.daemonset.priorityClassName }}
      priorityClassName: {{ . }}
{{- end }}
{{- with .Values.daemonset.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.daemonset.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.daemonset.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
