name: Lint Helm Chart

on:
  push:
    branches:
      - "!gh-pages"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        run: make ci:enable:helm

      - name: Setup Kubeval
        run: make ci:enable:kubeval

      - name: Check diff chart
        run: make ci:diff

      - name: Check chart version
        run: make ci:diff:chart | xargs -I{} /bin/bash -c "cd ./{} && ../.github/scripts/check-version.sh || exit 255"

      - name: Check lint
        run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make lint || exit 255"