name: Lint Helm Chart

on:
  push:
    branches-ignore:
      - "gh-pages"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        continue-on-error: true
        run: echo '${{ toJSON(github) }}'

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Check diff chart
        run: make ci:diff

      - name: Setup Helm
        run: make ci:enable:helm

      - name: Setup Kubeval
        run: make ci:enable:kubeval

      - name: Check chart version
        run: make ci:diff:chart | xargs -I{} /bin/bash -c "cd ./{} && ../.github/scripts/check-version.sh || exit 255"

      - name: Check lint
        run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make lint || exit 255"
